script:
- VERSION=latest make build.docker
jobs:
  include:
  - stage: build-push
    if: branch = master AND type != pull_request
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - VERSION=latest make build.push
env:
  global:
  - secure: QaPRqHJ2Isze3Hl2LdZI1XF0Wbor1AqIpi5441KDUPYZBSPtGWLO1EO8TqN3zhZT8+qC1LmlG2Jf63Q/5n7r5ourZ0sDpkw9xAl0xPQVTW7z0ZTQBRizFfEctn0E4kNifU8SNMwlO1ogFNsM9vj3JEi5W/F21VG3nmvfP6aDbsqLGc5ffa2Oz/iJWxf7lHJG/Cseg8Kh9ED8IZydpcSfjn/PEU9hZMiutemYC10hn+PWmcEbMmQs44SlvbSvL2S2lNAvLHMJ6RENQN0UD9tarkWg1o2eF+v/Eo5YNVm2IlEh1Ue6+sIj0AbV8TzKbQ6MV5Fir9KHPcUAHaE2GbL3eZfJj6TnlvtzMBk9Xdqlps+7rT6lEhgsqaXPPEOJMjRrnjJDUQtp+pZdgnyj+vXBAa2zkAC/cB3YMweGkzXX+70p6EzY7TxAG4vfLOB0fJwVnjnBrG9SgBDdhtZfGbW0w09RkA5cYdAqHrnILUyYEGZfDgO8NqgHFiIyFsa7oPS3zCTFQ0SOh42WaVV9kDcZjV78BFgU0VbmAq1mZAjKRonMIFGtXymY2XPmT0eYL7wBSGnaRxcm0h6GidrJAyE8Q7uuLG66wyCidrVUJkCMdxKNi361tOXy5LtSmsV02IFeWfbhKkzfhcQXDTpPQ9Xelv/WJ5eE++1Q2K01qmStKC0=
  - secure: R6QrZE9mF89I5Ba71S9RmcvAzPUNb+5UHt5CTKtW38S4IG7xNqVK9urLWBs2K8B1D2DK4ZMnnrUlddWCT10rscJ/cx1W+d9ba7zecMDnT6+b7EKm7Kd4yutpSSydxl3kyVrK/3mTfFF0Rdjn/fGomMx9Yuw34hb6/VwVsjiyL1QP5AqQ86bV8jQpuYTrBAqfnwgChEEhb+QD3ZcCG7KbKNm47rkrWVu8oSi4aHdiYHN8z4bwYLDJdfhIj4qHFScPIOZDkEtrI0arshnAvY+rYMokxIBfvihJFaczrMVxaHkVCLYjojEnrbeDk7Ya6m/TBqNQIZjhhdHEec1GUL+kfYsy/O9xThsDYD/1VFxQcZLyocH+3QnJrRus2oLOQy/CtdIAx3J6kbt2ONZDFLs2mM4k21sgQOnxUSbzFfTTKPvBB4LUbapGr1zyoe3UVKvLbD1WhEEzPvn89rfSAFP32VEK2mnZtEGZ1IdD5Ks0kdAKWaz/BxeBpyNdlLkFIf4yEBMHh3Y2cjcIE4RP4B9R7QeJEmgzyCwgDkiKOnV5LxKkJMGqPiu5ApOKF6qr6jGDn23qk7iKRzu0YouhWcFJCaSIxnB5hLRCBonJ/d7r9K3gsHt0AwP3LPNjtiB08qLS9kWjfHNePS27fLVPcDmY+xOy9X9TNaK/7sXVLjpvm/U=
